sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: TvicRT5cC6IIRMIDBbEPsK5aaSCZBm6ayt10QFLDffMLpyOqr6DD19mpE8umTGY/wMFmGST6ew326oJKc8AywKHZqbhFz/rzKYqOUD+JBnIBj2y6a9JmzfJ6Jv5eBfCTUPC/J4qE+bwow7m5QfgmPCr7UeSVuDniuO5ASYfaYdMsPDaV2wyRon4kSryw5E0T3rXa0J+mt5SXGLPgzBZBhifYV3rYMZCRauR9vnleP1DdcXzGaglv3lzHRT5sRp11LmAjySyFtLU/hFLf+xhGeZIarpYWVKpQfbirgdM/lhlKKPxBC/uHnVFizvzq6b1Fn0kn9wDaaux9/OKkexHKECn9bsFqMmky35FhXJdG1XDbUfelHHRrSMyROEJipJgP1sB+mKbyzQzPrpsKU5aboJJEUc8aS6GQ2AOoCD/Dr0hbtoy46FZq9EalNxVQZa2pxhvTzSf0zKY+eFq+0n8xXmSUKJNfF2kRMbnmOdjCP6QXKSGKvfZLR/26OmcrTwuztY8rA3NTk4ddUh0zErqImuEk0Dt618mNQLGtOt2XAbl8BdXRmNX93e4Ko4YHzlHTPsoJ1P31fD3CnXN5eg5gLQSASDn3JfIL/FqxamL3CZiyGR8mr42ek49Wcq9o7hzLQX14o3orY2ckedBTm5KGeWM/OYKTTnQu8FoYuMdiOBw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Visit-to-Iceland-and-the-Scandinavian-North_1894
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy